// Package registry provides IANA CBOR tag constants and a lookup API
// for well-known CBOR tags from the IANA "Concise Binary Object
// Representation (CBOR) Tags" registry.
//
// The constants and tag information in this package are derived from the
// IANA registry cache (registry.json) and generated by the
// cbor-registry-gen tool.
package registry
