// Code generated by cbor-registry-gen. DO NOT EDIT.

package registry

const (
	// TagDateTimeString is tag 0: Standard date/time string; see Section 3.4.1
	TagDateTimeString uint64 = 0

	// TagEpochDateTime is tag 1: Epoch-based date/time; see Section 3.4.2
	TagEpochDateTime uint64 = 1

	// TagUnsignedBignum is tag 2: Unsigned bignum; see Section 3.4.3
	TagUnsignedBignum uint64 = 2

	// TagNegativeBignum is tag 3: Negative bignum; see Section 3.4.3
	TagNegativeBignum uint64 = 3

	// TagDecimalFraction is tag 4: Decimal fraction; see Section 3.4.4
	TagDecimalFraction uint64 = 4

	// TagBigfloat is tag 5: Bigfloat; see Section 3.4.4
	TagBigfloat uint64 = 5

	// TagCOSEEncrypt0 is tag 16: COSE Single Recipient Encrypted Data Object
	TagCOSEEncrypt0 uint64 = 16

	// TagCOSEMac0 is tag 17: COSE Mac w/o Recipients Object
	TagCOSEMac0 uint64 = 17

	// TagCOSESign1 is tag 18: COSE Single Signer Data Object
	TagCOSESign1 uint64 = 18

	// TagCOSEStandaloneV2Countersignature is tag 19: COSE standalone V2 countersignature
	TagCOSEStandaloneV2Countersignature uint64 = 19

	// TagBase64URL is tag 21: Expected conversion to base64url encoding; see Section 3.4.5.2
	TagBase64URL uint64 = 21

	// TagBase64 is tag 22: Expected conversion to base64 encoding; see Section 3.4.5.2
	TagBase64 uint64 = 22

	// TagBase16 is tag 23: Expected conversion to base16 encoding; see Section 3.4.5.2
	TagBase16 uint64 = 23

	// TagEncodedCBOR is tag 24: Encoded CBOR data item; see Section 3.4.5.1
	TagEncodedCBOR uint64 = 24

	// TagReferenceTheNthPreviouslySeenString is tag 25: reference the nth previously seen string
	TagReferenceTheNthPreviouslySeenString uint64 = 25

	// TagSerialisedPerlObjectWithClassnameAndCons is tag 26: Serialised Perl object with classname and constructor arguments
	TagSerialisedPerlObjectWithClassnameAndCons uint64 = 26

	// TagSerialisedLanguageIndependentObjectWithT is tag 27: Serialised language-independent object with type name and constructor arguments
	TagSerialisedLanguageIndependentObjectWithT uint64 = 27

	// TagMarkValueAsPotentiallyShared is tag 28: mark value as (potentially) shared
	TagMarkValueAsPotentiallyShared uint64 = 28

	// TagReferenceNthMarkedValue is tag 29: reference nth marked value
	TagReferenceNthMarkedValue uint64 = 29

	// TagRationalNumber is tag 30: Rational number
	TagRationalNumber uint64 = 30

	// TagAbsentValueInACBORArray is tag 31: Absent value in a CBOR Array
	TagAbsentValueInACBORArray uint64 = 31

	// TagURI is tag 32: URI; see Section 3.4.5.3
	TagURI uint64 = 32

	// TagBase64URLText is tag 33: base64url; see Section 3.4.5.3
	TagBase64URLText uint64 = 33

	// TagBase64Text is tag 34: base64; see Section 3.4.5.3
	TagBase64Text uint64 = 34

	// TagRegexp is tag 35: Regular expression; see Section 2.4.4.3
	TagRegexp uint64 = 35

	// TagMIME is tag 36: MIME message; see Section 3.4.5.3
	TagMIME uint64 = 36

	// TagBinaryUUIDRFC9562Section4 is tag 37: Binary UUID ([RFC9562, Section 4])
	TagBinaryUUIDRFC9562Section4 uint64 = 37

	// TagLanguageTaggedString is tag 38: Language-tagged string
	TagLanguageTaggedString uint64 = 38

	// TagIdentifier is tag 39: Identifier
	TagIdentifier uint64 = 39

	// TagMultiDimensionalArrayRowMajorOrder is tag 40: Multi-dimensional Array, row-major order
	TagMultiDimensionalArrayRowMajorOrder uint64 = 40

	// TagHomogeneousArray is tag 41: Homogeneous Array
	TagHomogeneousArray uint64 = 41

	// TagIPLDContentIdentifier is tag 42: IPLD content identifier
	TagIPLDContentIdentifier uint64 = 42

	// TagYANGBitsDatatypeSeeSection67 is tag 43: YANG bits datatype; see Section 6.7.
	TagYANGBitsDatatypeSeeSection67 uint64 = 43

	// TagYANGEnumerationDatatypeSeeSection66 is tag 44: YANG enumeration datatype; see Section 6.6.
	TagYANGEnumerationDatatypeSeeSection66 uint64 = 44

	// TagYANGIdentityrefDatatypeSeeSection610 is tag 45: YANG identityref datatype; see Section 6.10.
	TagYANGIdentityrefDatatypeSeeSection610 uint64 = 45

	// TagYANGInstanceIdentifierDatatypeSeeSection is tag 46: YANG instance-identifier datatype; see Section 6.13.
	TagYANGInstanceIdentifierDatatypeSeeSection uint64 = 46

	// TagYANGSchemaItemIDentifierSidSeeSection32 is tag 47: YANG Schema Item iDentifier (sid); see Section 3.2.
	TagYANGSchemaItemIDentifierSidSeeSection32 uint64 = 47

	// TagIEEEMACAddress is tag 48: IEEE MAC Address
	TagIEEEMACAddress uint64 = 48

	// TagIPv4PrefixlenIPv4IPv4Prefixpart is tag 52: IPv4, [prefixlen,IPv4], [IPv4,prefixpart]
	TagIPv4PrefixlenIPv4IPv4Prefixpart uint64 = 52

	// TagIPv6PrefixlenIPv6IPv6Prefixpart is tag 54: IPv6, [prefixlen,IPv6], [IPv6,prefixpart]
	TagIPv6PrefixlenIPv6IPv6Prefixpart uint64 = 54

	// TagAnArrayClaimElementIntendedToBeRedactedO is tag 58: An array claim element intended to be redacted, or a map key whose key and va...
	TagAnArrayClaimElementIntendedToBeRedactedO uint64 = 58

	// TagASelectiveDisclosureRedactedArrayClaimEl is tag 60: A selective disclosure redacted (array) claim element. (TEMPORARY - registere...
	TagASelectiveDisclosureRedactedArrayClaimEl uint64 = 60

	// TagCBORWebTokenCWT is tag 61: CBOR Web Token (CWT)
	TagCBORWebTokenCWT uint64 = 61

	// TagAMarkerOfALocationInAMapOrAnArrayWhereAD is tag 62: A marker of a location in a map or an array where a decoy is intended to be i...
	TagAMarkerOfALocationInAMapOrAnArrayWhereAD uint64 = 62

	// TagEncodedCBORSequenceRFC8742 is tag 63: Encoded CBOR Sequence [RFC8742]
	TagEncodedCBORSequenceRFC8742 uint64 = 63

	// TagUint8TypedArray is tag 64: uint8 Typed Array
	TagUint8TypedArray uint64 = 64

	// TagUint16BigEndianTypedArray is tag 65: uint16, big endian, Typed Array
	TagUint16BigEndianTypedArray uint64 = 65

	// TagUint32BigEndianTypedArray is tag 66: uint32, big endian, Typed Array
	TagUint32BigEndianTypedArray uint64 = 66

	// TagUint64BigEndianTypedArray is tag 67: uint64, big endian, Typed Array
	TagUint64BigEndianTypedArray uint64 = 67

	// TagUint8TypedArrayClampedArithmetic is tag 68: uint8 Typed Array, clamped arithmetic
	TagUint8TypedArrayClampedArithmetic uint64 = 68

	// TagUint16LittleEndianTypedArray is tag 69: uint16, little endian, Typed Array
	TagUint16LittleEndianTypedArray uint64 = 69

	// TagUint32LittleEndianTypedArray is tag 70: uint32, little endian, Typed Array
	TagUint32LittleEndianTypedArray uint64 = 70

	// TagUint64LittleEndianTypedArray is tag 71: uint64, little endian, Typed Array
	TagUint64LittleEndianTypedArray uint64 = 71

	// TagSint8TypedArray is tag 72: sint8 Typed Array
	TagSint8TypedArray uint64 = 72

	// TagSint16BigEndianTypedArray is tag 73: sint16, big endian, Typed Array
	TagSint16BigEndianTypedArray uint64 = 73

	// TagSint32BigEndianTypedArray is tag 74: sint32, big endian, Typed Array
	TagSint32BigEndianTypedArray uint64 = 74

	// TagSint64BigEndianTypedArray is tag 75: sint64, big endian, Typed Array
	TagSint64BigEndianTypedArray uint64 = 75

	// TagReserved is tag 76: (reserved)
	TagReserved uint64 = 76

	// TagSint16LittleEndianTypedArray is tag 77: sint16, little endian, Typed Array
	TagSint16LittleEndianTypedArray uint64 = 77

	// TagSint32LittleEndianTypedArray is tag 78: sint32, little endian, Typed Array
	TagSint32LittleEndianTypedArray uint64 = 78

	// TagSint64LittleEndianTypedArray is tag 79: sint64, little endian, Typed Array
	TagSint64LittleEndianTypedArray uint64 = 79

	// TagIEEE754Binary16BigEndianTypedArray is tag 80: IEEE 754 binary16, big endian, Typed Array
	TagIEEE754Binary16BigEndianTypedArray uint64 = 80

	// TagIEEE754Binary32BigEndianTypedArray is tag 81: IEEE 754 binary32, big endian, Typed Array
	TagIEEE754Binary32BigEndianTypedArray uint64 = 81

	// TagIEEE754Binary64BigEndianTypedArray is tag 82: IEEE 754 binary64, big endian, Typed Array
	TagIEEE754Binary64BigEndianTypedArray uint64 = 82

	// TagIEEE754Binary128BigEndianTypedArray is tag 83: IEEE 754 binary128, big endian, Typed Array
	TagIEEE754Binary128BigEndianTypedArray uint64 = 83

	// TagIEEE754Binary16LittleEndianTypedArray is tag 84: IEEE 754 binary16, little endian, Typed Array
	TagIEEE754Binary16LittleEndianTypedArray uint64 = 84

	// TagIEEE754Binary32LittleEndianTypedArray is tag 85: IEEE 754 binary32, little endian, Typed Array
	TagIEEE754Binary32LittleEndianTypedArray uint64 = 85

	// TagIEEE754Binary64LittleEndianTypedArray is tag 86: IEEE 754 binary64, little endian, Typed Array
	TagIEEE754Binary64LittleEndianTypedArray uint64 = 86

	// TagIEEE754Binary128LittleEndianTypedArray is tag 87: IEEE 754 binary128, little endian, Typed Array
	TagIEEE754Binary128LittleEndianTypedArray uint64 = 87

	// TagCOSEEncrypt is tag 96: COSE Encrypted Data Object
	TagCOSEEncrypt uint64 = 96

	// TagCOSEMac is tag 97: COSE MACed Data Object
	TagCOSEMac uint64 = 97

	// TagCOSESign is tag 98: COSE Signed Data Object
	TagCOSESign uint64 = 98

	// TagCRIReference is tag 99: CRI Reference
	TagCRIReference uint64 = 99

	// TagNumberOfDaysSinceTheEpochDate19700101 is tag 100: Number of days since the epoch date 1970-01-01
	TagNumberOfDaysSinceTheEpochDate19700101 uint64 = 100

	// TagAlternativesAsGivenByTheUint128SeeSectio is tag 101: alternatives as given by the uint + 128; see Section 9.1
	TagAlternativesAsGivenByTheUint128SeeSectio uint64 = 101

	// TagGeographicCoordinates is tag 103: Geographic Coordinates
	TagGeographicCoordinates uint64 = 103

	// TagGeographicCoordinateReferenceSystemWKTOr is tag 104: Geographic Coordinate Reference System WKT or EPSG number
	TagGeographicCoordinateReferenceSystemWKTOr uint64 = 104

	// TagSUITEnvelopeAsDefinedInAppendixAOfRFCIet is tag 107: SUIT_Envelope as defined in Appendix A of [RFC-ietf-suit-manifest-34]
	TagSUITEnvelopeAsDefinedInAppendixAOfRFCIet uint64 = 107

	// TagExpectedConversionToBase16EncodingLowerc is tag 108: Expected conversion to base16 encoding (lowercase)
	TagExpectedConversionToBase16EncodingLowerc uint64 = 108

	// TagRelativeObjectIdentifierBEREncodingSDNVR is tag 110: relative object identifier (BER encoding); SDNV [RFC6256] sequence
	TagRelativeObjectIdentifierBEREncodingSDNVR uint64 = 110

	// TagObjectIdentifierBEREncoding is tag 111: object identifier (BER encoding)
	TagObjectIdentifierBEREncoding uint64 = 111

	// TagObjectIdentifierBEREncodingRelativeTo136 is tag 112: object identifier (BER encoding), relative to 1.3.6.1.4.1
	TagObjectIdentifierBEREncodingRelativeTo136 uint64 = 112

	// TagInternetOfThingsDataPoint is tag 120: Internet of Things Data Point
	TagInternetOfThingsDataPoint uint64 = 120

	// TagGordianEnvelope is tag 200: Gordian Envelope
	TagGordianEnvelope uint64 = 200

	// TagEnclosedDCBOR is tag 201: enclosed dCBOR
	TagEnclosedDCBOR uint64 = 201

	// TagMarkValueAsHavingStringReferences is tag 256: mark value as having string references
	TagMarkValueAsHavingStringReferences uint64 = 256

	// TagBinaryMIMEMessage is tag 257: Binary MIME message
	TagBinaryMIMEMessage uint64 = 257

	// TagMathSet is tag 258: Mathematical finite set
	TagMathSet uint64 = 258

	// TagMapDatatypeWithKeyValueOperationsEGGetSe is tag 259: Map datatype with key-value operations (e.g. `.get()/.set()/.delete()`)
	TagMapDatatypeWithKeyValueOperationsEGGetSe uint64 = 259

	// TagNetworkAddressIPv4OrIPv6OrMACAddressDEPR is tag 260: Network Address (IPv4 or IPv6 or MAC Address) (DEPRECATED in favor of 52 and ...
	TagNetworkAddressIPv4OrIPv6OrMACAddressDEPR uint64 = 260

	// TagNetworkAddressPrefixIPv4OrIPv6AddressMas is tag 261: Network Address Prefix (IPv4 or IPv6 Address + Mask Length) (DEPRECATED in fa...
	TagNetworkAddressPrefixIPv4OrIPv6AddressMas uint64 = 261

	// TagEmbeddedJSONObject is tag 262: Embedded JSON Object
	TagEmbeddedJSONObject uint64 = 262

	// TagHexadecimalString is tag 263: Hexadecimal string
	TagHexadecimalString uint64 = 263

	// TagDecimalFractionWithArbitraryExponent is tag 264: Decimal fraction with arbitrary exponent
	TagDecimalFractionWithArbitraryExponent uint64 = 264

	// TagBigfloatWithArbitraryExponent is tag 265: Bigfloat with arbitrary exponent
	TagBigfloatWithArbitraryExponent uint64 = 265

	// TagInternationalizedResourceIdentifierIRI is tag 266: Internationalized resource identifier (IRI)
	TagInternationalizedResourceIdentifierIRI uint64 = 266

	// TagInternationalizedResourceIdentifierRefer is tag 267: Internationalized resource identifier reference (IRI reference)
	TagInternationalizedResourceIdentifierRefer uint64 = 267

	// TagExtendedDecimalFraction is tag 268: Extended decimal fraction
	TagExtendedDecimalFraction uint64 = 268

	// TagExtendedBigfloat is tag 269: Extended bigfloat
	TagExtendedBigfloat uint64 = 269

	// TagExtendedRationalNumber is tag 270: Extended rational number
	TagExtendedRationalNumber uint64 = 270

	// TagDDoSOpenThreatSignalingDOTSSignalChannel is tag 271: DDoS Open Threat Signaling (DOTS) signal channel object, as defined in [RFC9132]
	TagDDoSOpenThreatSignalingDOTSSignalChannel uint64 = 271

	// TagNonUTF8CESU8String is tag 272: Non-UTF-8 CESU-8 string
	TagNonUTF8CESU8String uint64 = 272

	// TagNonUTF8WTF8String is tag 273: Non-UTF-8 WTF-8 string
	TagNonUTF8WTF8String uint64 = 273

	// TagNonUTF8MUTF8String is tag 274: Non-UTF-8 MUTF-8 string
	TagNonUTF8MUTF8String uint64 = 274

	// TagMapContainsOnlyKeysThatAreOfTypeTextStri is tag 275: Map contains only keys that are of type Text String (major type 3)
	TagMapContainsOnlyKeysThatAreOfTypeTextStri uint64 = 275

	// TagERISBinaryReadCapability is tag 276: ERIS binary read capability
	TagERISBinaryReadCapability uint64 = 276

	// TagUniversalGeographicalAreaDescriptionGADS is tag 277: Universal Geographical Area Description (GAD) shape; see Section 5
	TagUniversalGeographicalAreaDescriptionGADS uint64 = 277

	// TagUniversalGeographicalAreaDescriptionGADD is tag 278: Universal Geographical Area Description (GAD) description of velocity; see Se...
	TagUniversalGeographicalAreaDescriptionGADD uint64 = 278

	// TagCoordinateReferenceSystemWrapper is tag 279: Coordinate Reference System Wrapper
	TagCoordinateReferenceSystemWrapper uint64 = 279

	// TagSymbol is tag 280: Symbol
	TagSymbol uint64 = 280

	// TagLinkedList is tag 281: Linked list
	TagLinkedList uint64 = 281

	// TagCharacter is tag 282: Character
	TagCharacter uint64 = 282

	// TagObject is tag 283: Object
	TagObject uint64 = 283

	// TagJSONNumericValueRepresentedAsItsJSONText is tag 284: JSON Numeric Value, Represented as its JSON Text
	TagJSONNumericValueRepresentedAsItsJSONText uint64 = 284

	// TagSUITReportProtected is tag 285: SUIT_Report_Protected
	TagSUITReportProtected uint64 = 285

	// TagSUITReference is tag 286: SUIT_Reference
	TagSUITReference uint64 = 286

	// TagSUITCapabilityReport is tag 287: SUIT_Capability_Report
	TagSUITCapabilityReport uint64 = 287

	// TagIsolateSharedValuesWithinThisScope is tag 296: isolate shared values within this scope
	TagIsolateSharedValuesWithinThisScope uint64 = 296

	// TagGeohashString is tag 301: Geohash String
	TagGeohashString uint64 = 301

	// TagEarmarkedForCoRIM is tag 500: Earmarked for CoRIM
	TagEarmarkedForCoRIM uint64 = 500

	// TagACBORTagThatContainsACorimMap is tag 501: A CBOR tag that contains a corim-map.
	TagACBORTagThatContainsACorimMap uint64 = 501

	// TagACBORTagThatContainsAConciseswidTagMap is tag 505: A CBOR tag that contains a conciseswid-tag-map.
	TagACBORTagThatContainsAConciseswidTagMap uint64 = 505

	// TagACBORTagThatContainsAConcisemidTagMap is tag 506: A CBOR tag that contains a concisemid-tag-map.
	TagACBORTagThatContainsAConcisemidTagMap uint64 = 506

	// TagACBORTagThatContainsAnXcorimMap is tag 526: A CBOR tag that contains an xcorim-map.
	TagACBORTagThatContainsAnXcorimMap uint64 = 526

	// TagACBORTagThatContainsEitherXcorimmapOrSig is tag 527: A CBOR tag that contains either: xcorimmap, or signed-xcorim.
	TagACBORTagThatContainsEitherXcorimmapOrSig uint64 = 527

	// TagACBORTagThatContainsAUEIDBetween7And33By is tag 550: A CBOR tag that contains a UEID between 7 and 33 bytes.
	TagACBORTagThatContainsAUEIDBetween7And33By uint64 = 550

	// TagEarmarkedForCoRIM_551 is tag 551: Earmarked for CoRIM
	TagEarmarkedForCoRIM_551 uint64 = 551

	// TagACBORTagThatContainsASecurityVersionNumb is tag 552: A CBOR tag that contains a security version number that is evaluated with equ...
	TagACBORTagThatContainsASecurityVersionNumb uint64 = 552

	// TagACBORTagThatContainsMinSvnThatIdentifies is tag 553: A CBOR tag that contains min-svn that identifies a security version number th...
	TagACBORTagThatContainsMinSvnThatIdentifies uint64 = 553

	// TagACBORTagThatContainsAPEMEncodedSubjectPu is tag 554: A CBOR tag that contains a PEM encoded SubjectPublicKeyInfo. See Section 13 o...
	TagACBORTagThatContainsAPEMEncodedSubjectPu uint64 = 554

	// TagACBORTagThatContainsAPEMEncodedSubjectPu_555 is tag 555: A CBOR tag that contains a PEM encoded SubjectPublicKeyInfo. See Section 13 o...
	TagACBORTagThatContainsAPEMEncodedSubjectPu_555 uint64 = 555

	// TagACBORTagThatContainsAnX509CertificateCha is tag 556: A CBOR tag that contains an X.509 certificate chain created by the concatenat...
	TagACBORTagThatContainsAnX509CertificateCha uint64 = 556

	// TagACBORTagThatContainsAByteStringInterpret is tag 560: A CBOR tag that contains a byte string interpreted as an array of bits.
	TagACBORTagThatContainsAByteStringInterpret uint64 = 560

	// TagSpdmTocMap is tag 570: spdm-toc-map
	TagSpdmTocMap uint64 = 570

	// TagConciseEvidenceMap is tag 571: concise-evidence-map
	TagConciseEvidenceMap uint64 = 571

	// TagUnprotectedCWTClaimsSetRFC9781 is tag 601: Unprotected CWT Claims Set [RFC9781]
	TagUnprotectedCWTClaimsSetRFC9781 uint64 = 601

	// TagDetachedEATBundle is tag 602: Detached EAT Bundle
	TagDetachedEATBundle uint64 = 602

	// TagExtendedTime is tag 1001: extended time
	TagExtendedTime uint64 = 1001

	// TagDuration is tag 1002: duration
	TagDuration uint64 = 1002

	// TagPeriod is tag 1003: period
	TagPeriod uint64 = 1003

	// TagRFC3339FullDateString is tag 1004: [RFC3339] full-date string
	TagRFC3339FullDateString uint64 = 1004

	// TagObjectTypeIdentifier is tag 1010: Object type identifier
	TagObjectTypeIdentifier uint64 = 1010

	// TagMultiDimensionalArrayColumnMajorOrder is tag 1040: Multi-dimensional Array, column-major order
	TagMultiDimensionalArrayColumnMajorOrder uint64 = 1040

	// TagIEEEOUICID is tag 1048: IEEE OUI/CID
	TagIEEEOUICID uint64 = 1048

	// TagSUITManifestAsDefinedInAppendixAOfRFCIet is tag 1070: SUIT_Manifest as defined in Appendix A of [RFC-ietf-suit-manifest-34]
	TagSUITManifestAsDefinedInAppendixAOfRFCIet uint64 = 1070

	// TagCOSEAlgorithmIdentifierBaseHashValue is tag 18556: [COSE algorithm identifier, Base Hash value]
	TagCOSEAlgorithmIdentifierBaseHashValue uint64 = 18556

	// TagDescriptionOfTheValueInsteadOfTheValueIt is tag 20853: description of the value instead of the value itself
	TagDescriptionOfTheValueInsteadOfTheValueIt uint64 = 20853

	// TagIRegexp is tag 21065: I-Regexp
	TagIRegexp uint64 = 21065

	// TagECMAScriptRegExpHttps262EcmaInternationa is tag 21066: ECMAScript RegExp [https://262.ecma-international.org/14.0/#sec-regexp-regula...
	TagECMAScriptRegExpHttps262EcmaInternationa uint64 = 21066

	// TagAlwaysInvalidInInterchangeProgrammingAid is tag 21334: (always invalid in interchange) programming aid for simple values
	TagAlwaysInvalidInInterchangeProgrammingAid uint64 = 21334

	// TagACBORTagIdentifier is tag 21607: a CBOR Tag identifier
	TagACBORTagIdentifier uint64 = 21607

	// TagHintThatIndicatesAnAdditionalLevelOfIndi is tag 22098: hint that indicates an additional level of indirection
	TagHintThatIndicatesAnAdditionalLevelOfIndi uint64 = 22098

	// TagCapture3 is tag 25441: Capture [3]
	TagCapture3 uint64 = 25441

	// TagIdentifierForAFHIRConstant is tag 32768: Identifier for a FHIR constant
	TagIdentifierForAFHIRConstant uint64 = 32768

	// TagExternalReference is tag 32769: External reference
	TagExternalReference uint64 = 32769

	// TagLogicalOperatorNONENOTEncodesTheLogicalO is tag 32870: Logical operator: NONE / NOT. Encodes the logical operation (!item1&&!item2&&...
	TagLogicalOperatorNONENOTEncodesTheLogicalO uint64 = 32870

	// TagLogicalOperatorANYEncodesTheLogicalOpera is tag 32871: Logical operator: ANY. Encodes the logical operation (item1||item2||item3||...).
	TagLogicalOperatorANYEncodesTheLogicalOpera uint64 = 32871

	// TagLogicalOperatorALLEncodesTheLogicalOpera is tag 32872: Logical operator: ALL. Encodes the logical operation (item1&&item2&&item3&&...).
	TagLogicalOperatorALLEncodesTheLogicalOpera uint64 = 32872

	// TagUrKnownValueSemanticSignifier is tag 40000: ur:known-value, Semantic signifier
	TagUrKnownValueSemanticSignifier uint64 = 40000

	// TagUrDigest32ByteSHA256Digest is tag 40001: ur:digest, 32-byte SHA-256 digest
	TagUrDigest32ByteSHA256Digest uint64 = 40001

	// TagUrEncryptedIETFChaCha20Poly1305RFC8439En is tag 40002: ur:encrypted, IETF ChaCha20-Poly1305 ([RFC8439]) encrypted message
	TagUrEncryptedIETFChaCha20Poly1305RFC8439En uint64 = 40002

	// TagUrCompressedRFC1951DEFLATECompressedMess is tag 40003: ur:compressed, [RFC1951] DEFLATE-compressed message
	TagUrCompressedRFC1951DEFLATECompressedMess uint64 = 40003

	// TagUrRequestTransactionRequestIdentifier is tag 40004: ur:request, Transaction Request identifier
	TagUrRequestTransactionRequestIdentifier uint64 = 40004

	// TagUrResponseTransactionResponseIdentifier is tag 40005: ur:response, Transaction response identifier
	TagUrResponseTransactionResponseIdentifier uint64 = 40005

	// TagUrFunctionEnvelopeExpressionFunctionIden is tag 40006: ur:function, Envelope expression function identifier
	TagUrFunctionEnvelopeExpressionFunctionIden uint64 = 40006

	// TagUrParameterEnvelopeExpressionParameterId is tag 40007: ur:parameter, Envelope expression parameter identifier
	TagUrParameterEnvelopeExpressionParameterId uint64 = 40007

	// TagUrPlaceholderEnvelopeExpressionPlacehold is tag 40008: ur:placeholder, Envelope expression placeholder identifier
	TagUrPlaceholderEnvelopeExpressionPlacehold uint64 = 40008

	// TagUrReplacementEnvelopeExpressionReplaceme is tag 40009: ur:replacement, Envelope expression replacement identifier
	TagUrReplacementEnvelopeExpressionReplaceme uint64 = 40009

	// TagUrAgreementPrivateKeyCurve25519PrivateKe is tag 40010: ur:agreement-private-key, Curve25519 private key for X25519 key agreement
	TagUrAgreementPrivateKeyCurve25519PrivateKe uint64 = 40010

	// TagUrAgreementPublicKeyCurve25519PublicKeyF is tag 40011: ur:agreement-public-key, Curve25519 public key for X25519 key agreement
	TagUrAgreementPublicKeyCurve25519PublicKeyF uint64 = 40011

	// TagUrAridApparentlyRandomIdentifier is tag 40012: ur:arid, Apparently Random Identifier
	TagUrAridApparentlyRandomIdentifier uint64 = 40012

	// TagUrCryptoPrvkeysPrivateKeysForCryptograph is tag 40013: ur:crypto-prvkeys, Private keys for cryptographic operations
	TagUrCryptoPrvkeysPrivateKeysForCryptograph uint64 = 40013

	// TagUrNonceCryptographicNonce is tag 40014: ur:nonce, Cryptographic nonce
	TagUrNonceCryptographicNonce uint64 = 40014

	// TagUrPasswordScryptHashedPassword is tag 40015: ur:password, Scrypt-hashed password
	TagUrPasswordScryptHashedPassword uint64 = 40015

	// TagUrCryptoPrvkeysPrivateKeyBaseKeyMaterial is tag 40016: ur:crypto-prvkeys, Private key base (key material)
	TagUrCryptoPrvkeysPrivateKeyBaseKeyMaterial uint64 = 40016

	// TagUrCryptoPubkeysPublicKeyBaseSigningAndAg is tag 40017: ur:crypto-pubkeys, Public key base (signing and agreement public key bundle)
	TagUrCryptoPubkeysPublicKeyBaseSigningAndAg uint64 = 40017

	// TagUrSaltRandomSaltUsedForHashTreeDecorrela is tag 40018: ur:salt, Random salt used for hash tree decorrelation
	TagUrSaltRandomSaltUsedForHashTreeDecorrela uint64 = 40018

	// TagUrCryptoSealedEncryptedMessageAndEphemer is tag 40019: ur:crypto-sealed, Encrypted message and ephemeral public key
	TagUrCryptoSealedEncryptedMessageAndEphemer uint64 = 40019

	// TagUrSignatureCryptographicSignature is tag 40020: ur:signature, Cryptographic signature
	TagUrSignatureCryptographicSignature uint64 = 40020

	// TagUrSigningPrivateKeyCryptographicPrivateK is tag 40021: ur:signing-private-key, Cryptographic private key used for signing
	TagUrSigningPrivateKeyCryptographicPrivateK uint64 = 40021

	// TagUrSigningPublicKeyCryptographicPublicKey is tag 40022: ur:signing-public-key, Cryptographic public key used for signing
	TagUrSigningPublicKeyCryptographicPublicKey uint64 = 40022

	// TagUrCryptoKeyCryptographicKeyUsedForSymmet is tag 40023: ur:crypto-key, Cryptographic key used for symmetric encryption
	TagUrCryptoKeyCryptographicKeyUsedForSymmet uint64 = 40023

	// TagUrXidExtensibleIdentifierOrXIDDocument is tag 40024: ur:xid, Extensible identifier or XID Document
	TagUrXidExtensibleIdentifierOrXIDDocument uint64 = 40024

	// TagUrReferenceCryptographicallySecureRefere is tag 40025: ur:reference, Cryptographically secure reference to an object
	TagUrReferenceCryptographicallySecureRefere uint64 = 40025

	// TagUrEventEventIdentifier is tag 40026: ur:event, Event identifier
	TagUrEventEventIdentifier uint64 = 40026

	// TagUrEncryptedKeyContentKeyEncryptedWithADe is tag 40027: ur:encrypted-key, Content key encrypted with a derivation function
	TagUrEncryptedKeyContentKeyEncryptedWithADe uint64 = 40027

	// TagUrMlkemPrivateKeyPrivateKeyForMLKEMKeyEn is tag 40100: ur:mlkem-private-key, Private key for MLKEM key encapsulation
	TagUrMlkemPrivateKeyPrivateKeyForMLKEMKeyEn uint64 = 40100

	// TagUrMlkemPublicKeyPublicKeyForMLKEMKeyEnca is tag 40101: ur:mlkem-public-key, Public key for MLKEM key encapsulation
	TagUrMlkemPublicKeyPublicKeyForMLKEMKeyEnca uint64 = 40101

	// TagUrMlkemCiphertextCiphertextForMLKEMKeyEn is tag 40102: ur:mlkem-ciphertext, Ciphertext for MLKEM key encapsulation
	TagUrMlkemCiphertextCiphertextForMLKEMKeyEn uint64 = 40102

	// TagUrMldsaPrivateKeyPrivateKeyForMLDSASigna is tag 40103: ur:mldsa-private-key, Private key for MLDSA signature generation
	TagUrMldsaPrivateKeyPrivateKeyForMLDSASigna uint64 = 40103

	// TagUrMldsaPublicKeyPublicKeyForMLDSASignatu is tag 40104: ur:mldsa-public-key, Public key for MLDSA signature verification
	TagUrMldsaPublicKeyPublicKeyForMLDSASignatu uint64 = 40104

	// TagUrMldsaSignatureMLDSASignature is tag 40105: ur:mldsa-signature, MLDSA signature
	TagUrMldsaSignatureMLDSASignature uint64 = 40105

	// TagUrSeedCryptographicSeed is tag 40300: ur:seed, Cryptographic seed
	TagUrSeedCryptographicSeed uint64 = 40300

	// TagUrHdkeyBitcoinBIP32HDKey is tag 40303: ur:hdkey, Bitcoin BIP-32 HD key
	TagUrHdkeyBitcoinBIP32HDKey uint64 = 40303

	// TagUrKeypathBitcoinBIP32KeyDerivationPath is tag 40304: ur:keypath, Bitcoin BIP-32 key derivation path
	TagUrKeypathBitcoinBIP32KeyDerivationPath uint64 = 40304

	// TagUrCoinInfoCryptographicAssetAndNetworkSp is tag 40305: ur:coin-info, Cryptographic asset and network specifier
	TagUrCoinInfoCryptographicAssetAndNetworkSp uint64 = 40305

	// TagUrEckeyBitcoinEllipticCurveKeyPrivateOrP is tag 40306: ur:eckey, Bitcoin elliptic curve key (private or public)
	TagUrEckeyBitcoinEllipticCurveKeyPrivateOrP uint64 = 40306

	// TagUrAddressCryptocurrencyAddress is tag 40307: ur:address, Cryptocurrency address
	TagUrAddressCryptocurrencyAddress uint64 = 40307

	// TagUrOutputDescriptorBitcoinOutputDescripto is tag 40308: ur:output-descriptor, Bitcoin output descriptor
	TagUrOutputDescriptorBitcoinOutputDescripto uint64 = 40308

	// TagUrSskrShardedSecretKeyReconstructionSSKR is tag 40309: ur:sskr, Sharded Secret Key Reconstruction (SSKR) share
	TagUrSskrShardedSecretKeyReconstructionSSKR uint64 = 40309

	// TagUrPsbtPartiallySignedBitcoinTransaction is tag 40310: ur:psbt, Partially Signed Bitcoin Transaction
	TagUrPsbtPartiallySignedBitcoinTransaction uint64 = 40310

	// TagUrAccountDescriptorBitcoinAccountDescrip is tag 40311: ur:account-descriptor, Bitcoin account descriptor
	TagUrAccountDescriptorBitcoinAccountDescrip uint64 = 40311

	// TagUrSshPrivateTextFormatSSHPrivateKey is tag 40800: ur:ssh-private, Text format SSH private key
	TagUrSshPrivateTextFormatSSHPrivateKey uint64 = 40800

	// TagUrSshPublicTextFormatSSHPublicKey is tag 40801: ur:ssh-public, Text format SSH public key
	TagUrSshPublicTextFormatSSHPublicKey uint64 = 40801

	// TagUrSshSignatureTextFormatSSHSignature is tag 40802: ur:ssh-signature, Text format SSH signature
	TagUrSshSignatureTextFormatSSHSignature uint64 = 40802

	// TagUrSshCertificateTextFormatSSHCertificate is tag 40803: ur:ssh-certificate, Text format SSH certificate
	TagUrSshCertificateTextFormatSSHCertificate uint64 = 40803

	// TagConcordiumSmartContractAddress is tag 40919: Concordium smart contract address
	TagConcordiumSmartContractAddress uint64 = 40919

	// TagFraction is tag 41728: Fraction
	TagFraction uint64 = 41728

	// TagFractionNaNSignals is tag 41729: Fraction (-NaN signals)
	TagFractionNaNSignals uint64 = 41729

	// TagFractionNaNSignals_41730 is tag 41730: Fraction (+NaN signals)
	TagFractionNaNSignals_41730 uint64 = 41730

	// TagFractionBothNaNsSignal is tag 41731: Fraction (Both NaNs signal)
	TagFractionBothNaNsSignal uint64 = 41731

	// TagAConfidentialityClearanceTheKeyValuePair is tag 42600: A confidentiality clearance. The key value pairs of the map are defined in AD...
	TagAConfidentialityClearanceTheKeyValuePair uint64 = 42600

	// TagAMetadataBindingTheElementsOfTheArrayAre is tag 42601: A metadata binding. The elements of the array are defined in AdatP-4778.8. Th...
	TagAMetadataBindingTheElementsOfTheArrayAre uint64 = 42601

	// TagACollectionOfNCMSMetadataElementsTheKeyV is tag 42602: A collection of NCMS metadata elements. The key value pairs of the map are de...
	TagACollectionOfNCMSMetadataElementsTheKeyV uint64 = 42602

	// TagSingleComplexNumberArrayElementsAreRealI is tag 43000: Single complex number: array elements are real (I) and imaginary (Q) components
	TagSingleComplexNumberArrayElementsAreRealI uint64 = 43000

	// TagArrayOfComplexNumbersInInterleavedFormCo is tag 43001: Array of complex numbers in interleaved form: complex value k is stored with ...
	TagArrayOfComplexNumbersInInterleavedFormCo uint64 = 43001

	// TagPlatformVISID is tag 50000: PlatformV_IS_ID
	TagPlatformVISID uint64 = 50000

	// TagPlatformVISNAME is tag 50001: PlatformV_IS_NAME
	TagPlatformVISNAME uint64 = 50001

	// TagPlatformVISVALUE is tag 50002: PlatformV_IS_VALUE
	TagPlatformVISVALUE uint64 = 50002

	// TagPlatformVHASCOMPOSITEVALUE is tag 50003: PlatformV_HAS_COMPOSITE_VALUE
	TagPlatformVHASCOMPOSITEVALUE uint64 = 50003

	// TagPlatformVHASMAPPEDVALUE is tag 50004: PlatformV_HAS_MAPPED_VALUE
	TagPlatformVHASMAPPEDVALUE uint64 = 50004

	// TagPlatformVHASOBJID is tag 50005: PlatformV_HAS_OBJ_ID
	TagPlatformVHASOBJID uint64 = 50005

	// TagPlatformVHASOBJTAG is tag 50006: PlatformV_HAS_OBJ_TAG
	TagPlatformVHASOBJTAG uint64 = 50006

	// TagPlatformVHASCHILD is tag 50007: PlatformV_HAS_CHILD
	TagPlatformVHASCHILD uint64 = 50007

	// TagPlatformVHASPROPERTY is tag 50008: PlatformV_HAS_PROPERTY
	TagPlatformVHASPROPERTY uint64 = 50008

	// TagPlatformVHASMETA is tag 50009: PlatformV_HAS_META
	TagPlatformVHASMETA uint64 = 50009

	// TagPlatformVHASEVENT is tag 50010: PlatformV_HAS_EVENT
	TagPlatformVHASEVENT uint64 = 50010

	// TagPlatformVHASACTION is tag 50011: PlatformV_HAS_ACTION
	TagPlatformVHASACTION uint64 = 50011

	// TagPlatformVISTYPE is tag 50012: PlatformV_IS_TYPE
	TagPlatformVISTYPE uint64 = 50012

	// TagATagValueOf51997IndicatesThatThePayloadI is tag 51997: A tag value of 51997 indicates that the payload is CBOR-LD.
	TagATagValueOf51997IndicatesThatThePayloadI uint64 = 51997

	// TagSelfDescribe is tag 55799: Self-described CBOR; see Section 3.4.6
	TagSelfDescribe uint64 = 55799

	// TagIndicatesThatTheFileContainsCBORSequence is tag 55800: indicates that the file contains CBOR Sequences
	TagIndicatesThatTheFileContainsCBORSequence uint64 = 55800

	// TagIndicatesThatTheFileStartsWithACBORLabel is tag 55801: indicates that the file starts with a CBOR-Labeled Non-CBOR Data label.
	TagIndicatesThatTheFileStartsWithACBORLabel uint64 = 55801

	// TagCompressedByteString is tag 56500: Compressed byte string
	TagCompressedByteString uint64 = 56500

	// TagIdentifyAndDefineASetOfRecordStructuresE is tag 57342: Identify and define a set of record structures (each a sequence of property n...
	TagIdentifyAndDefineASetOfRecordStructuresE uint64 = 57342

	// TagIdentifyAndDefineARecordStructureASequen is tag 57343: Identify and define a record structure (a sequence of property names), and us...
	TagIdentifyAndDefineARecordStructureASequen uint64 = 57343

	// TagTheTaggedCBORArrayContainsAttestationEvi is tag 60000: The tagged CBOR array contains attestation evidence data with an Intel TEE qu...
	TagTheTaggedCBORArrayContainsAttestationEvi uint64 = 60000

	// TagTheTaggedCBORArrayContainsAttestationEvi_60001 is tag 60001: The tagged CBOR array contains attestation evidence data with an Intel TEE re...
	TagTheTaggedCBORArrayContainsAttestationEvi_60001 uint64 = 60001

	// TagTheTaggedCBORArrayContainsAttestationEvi_60002 is tag 60002: The tagged CBOR array contains attestation evidence data with an Intel SGX re...
	TagTheTaggedCBORArrayContainsAttestationEvi_60002 uint64 = 60002

	// TagTheTaggedCBORArrayContainingANumericExpr is tag 60010: The tagged CBOR array containing a numeric expression.
	TagTheTaggedCBORArrayContainingANumericExpr uint64 = 60010

	// TagTheTaggedCBORArrayContainingASetOfDigest is tag 60020: The tagged CBOR array containing a set of digests expression.
	TagTheTaggedCBORArrayContainingASetOfDigest uint64 = 60020

	// TagTheTaggedCBORArrayContainingASetOfString is tag 60021: The tagged CBOR array containing a set of strings expression.
	TagTheTaggedCBORArrayContainingASetOfString uint64 = 60021

	// TagAlwaysInvalidSeeSection101 is tag 65535: always invalid; see Section 10.1
	TagAlwaysInvalidSeeSection101 uint64 = 65535

	// TagRAINSMessage is tag 15309736: RAINS Message
	TagRAINSMessage uint64 = 15309736

	// TagTCGDICEProtectionEnvironmentProfileDescr is tag 1146111423: TCG DICE Protection Environment profile descriptor
	TagTCGDICEProtectionEnvironmentProfileDescr uint64 = 1146111423

	// TagMoaTChangeOfStatusMarker is tag 1298360423: MoaT change-of-status marker
	TagMoaTChangeOfStatusMarker uint64 = 1298360423

	// TagMoaTEndOfFileMarker is tag 1298493254: MoaT end-of-file marker
	TagMoaTEndOfFileMarker uint64 = 1298493254

	// TagMoaTFileIdentifierDetails is tag 1299145044: MoaT file identifier / details
	TagMoaTFileIdentifierDetails uint64 = 1299145044

	// TagACBOREncodedOpenswanConfigurationFileAsS is tag 1330664270: A CBOR encoded Openswan configuration file, as stored on disk for unit test c...
	TagACBOREncodedOpenswanConfigurationFileAsS uint64 = 1330664270

	// TagACryptographicallyAnchoredDataStructureU is tag 1347571280: A cryptographically anchored data structure used for digital authorship attes...
	TagACryptographicallyAnchoredDataStructureU uint64 = 1347571280

	// TagACryptographicPointerToAFullProofOfProce is tag 1347571281: A cryptographic pointer to a full Proof of Process Evidence Packet, used for ...
	TagACryptographicPointerToAFullProofOfProce uint64 = 1347571281

	// TagUrProvenanceProvenanceMark is tag 1347571542: ur:provenance, Provenance Mark
	TagUrProvenanceProvenanceMark uint64 = 1347571542

	// TagConciseSoftwareIdentifierCoSWID is tag 1398229316: Concise Software Identifier (CoSWID)
	TagConciseSoftwareIdentifierCoSWID uint64 = 1398229316

	// TagExplicitlyNone is tag 1413829460: Explicitly none.
	TagExplicitlyNone uint64 = 1413829460

	// TagAnAttestationResultStructureProducedByVe is tag 1463894560: An Attestation Result structure produced by Verifiers appraising Proof of Pro...
	TagAnAttestationResultStructureProducedByVe uint64 = 1463894560

	// TagArrayOfContentAddressedBlocksAndERISRead is tag 1701996915: Array of content-addressed blocks and ERIS read capabilities
	TagArrayOfContentAddressedBlocksAndERISRead uint64 = 1701996915

	// TagERISFSImageHeader is tag 1701996916: ERIS-FS image header
	TagERISFSImageHeader uint64 = 1701996916

	// TagAlwaysInvalidSeeSection101_4294967295 is tag 4294967295: always invalid; see Section 10.1
	TagAlwaysInvalidSeeSection101_4294967295 uint64 = 4294967295

	// TagIntelFPGASPDMManifest is tag 4294967296: Intel FPGA SPDM Manifest
	TagIntelFPGASPDMManifest uint64 = 4294967296

	// TagAlwaysInvalidSection101 is tag 18446744073709551615: always invalid; Section 10.1
	TagAlwaysInvalidSection101 uint64 = 18446744073709551615
)
