// Code generated by cbor-registry-gen. DO NOT EDIT.

package registry

// CBOR tag constants from the IANA "Concise Binary Object Representation
// (CBOR) Tags" registry.
const (
	// TagDateTimeString is tag 0: Standard date/time string; see Section 3.4.1 of RFC 8949.
	TagDateTimeString uint64 = 0

	// TagEpochDateTime is tag 1: Epoch-based date/time; see Section 3.4.2 of RFC 8949.
	TagEpochDateTime uint64 = 1

	// TagUnsignedBignum is tag 2: Unsigned bignum; see Section 3.4.3 of RFC 8949.
	TagUnsignedBignum uint64 = 2

	// TagNegativeBignum is tag 3: Negative bignum; see Section 3.4.3 of RFC 8949.
	TagNegativeBignum uint64 = 3

	// TagDecimalFraction is tag 4: Decimal fraction.
	TagDecimalFraction uint64 = 4

	// TagBigfloat is tag 5: Bigfloat.
	TagBigfloat uint64 = 5

	// TagCOSEEncrypt0 is tag 16: COSE Single Recipient Encrypted Data Object.
	TagCOSEEncrypt0 uint64 = 16

	// TagCOSEMac0 is tag 17: COSE Mac w/o Recipients Object.
	TagCOSEMac0 uint64 = 17

	// TagCOSESign1 is tag 18: COSE Single Signer Data Object.
	TagCOSESign1 uint64 = 18

	// TagBase64URL is tag 21: Expected conversion to base64url encoding.
	TagBase64URL uint64 = 21

	// TagBase64 is tag 22: Expected conversion to base64 encoding.
	TagBase64 uint64 = 22

	// TagBase16 is tag 23: Expected conversion to base16 encoding.
	TagBase16 uint64 = 23

	// TagEncodedCBOR is tag 24: Encoded CBOR data item.
	TagEncodedCBOR uint64 = 24

	// TagURI is tag 32: URI.
	TagURI uint64 = 32

	// TagBase64URLText is tag 33: base64url.
	TagBase64URLText uint64 = 33

	// TagBase64Text is tag 34: base64.
	TagBase64Text uint64 = 34

	// TagRegexp is tag 35: Regular expression.
	TagRegexp uint64 = 35

	// TagMIME is tag 36: MIME message.
	TagMIME uint64 = 36

	// TagCOSEEncrypt is tag 96: COSE Encrypted Data Object.
	TagCOSEEncrypt uint64 = 96

	// TagCOSEMac is tag 97: COSE MACed Data Object.
	TagCOSEMac uint64 = 97

	// TagCOSESign is tag 98: COSE Signed Data Object.
	TagCOSESign uint64 = 98

	// TagMathSet is tag 258: Mathematical finite set.
	TagMathSet uint64 = 258

	// TagSelfDescribe is tag 55799: Self-Described CBOR.
	TagSelfDescribe uint64 = 55799
)
