// Command cbor-registry-gen generates Go source code containing CBOR tag
// constants and registry data from a JSON cache of the IANA CBOR Tags registry.
//
// Usage:
//
//	go run ./cmd/cbor-registry-gen -cache registry/registry.json -out registry/tags_gen.go -package registry
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"unicode"
)

type cacheFile struct {
	FetchedAt string     `json:"fetched_at"`
	Source    string     `json:"source"`
	Tags      []tagEntry `json:"tags"`
}

type tagEntry struct {
	Tag       uint64 `json:"tag"`
	DataItem  string `json:"data_item"`
	Semantics string `json:"semantics"`
	Reference string `json:"reference"`
}

var tagNames = map[uint64]string{
	0:     "DateTimeString",
	1:     "EpochDateTime",
	2:     "UnsignedBignum",
	3:     "NegativeBignum",
	4:     "DecimalFraction",
	5:     "Bigfloat",
	16:    "COSEEncrypt0",
	17:    "COSEMac0",
	18:    "COSESign1",
	21:    "Base64URL",
	22:    "Base64",
	23:    "Base16",
	24:    "EncodedCBOR",
	32:    "URI",
	33:    "Base64URLText",
	34:    "Base64Text",
	35:    "Regexp",
	36:    "MIME",
	55799: "SelfDescribe",
	96:    "COSEEncrypt",
	97:    "COSEMac",
	98:    "COSESign",
	258:   "MathSet",
}

func main() {
	cachePath := flag.String("cache", "", "path to registry.json cache file")
	outPath := flag.String("out", "", "output file path (default: stdout)")
	pkgName := flag.String("package", "registry", "package name for generated code")
	subset := flag.String("subset", "", "comma-separated tag numbers to include (default: all)")
	flag.Parse()

	if *cachePath == "" {
		fmt.Fprintf(os.Stderr, "error: -cache flag is required\n")
		os.Exit(1)
	}

	data, err := os.ReadFile(*cachePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading cache: %v\n", err)
		os.Exit(1)
	}

	var cache cacheFile
	if err := json.Unmarshal(data, &cache); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing cache: %v\n", err)
		os.Exit(1)
	}

	tags := cache.Tags
	if *subset != "" {
		allowed := parseSubset(*subset)
		var filtered []tagEntry
		for _, t := range tags {
			if allowed[t.Tag] {
				filtered = append(filtered, t)
			}
		}
		tags = filtered
	}

	sort.Slice(tags, func(i, j int) bool {
		return tags[i].Tag < tags[j].Tag
	})

	out := os.Stdout
	if *outPath != "" {
		f, err := os.Create(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error creating output: %v\n", err)
			os.Exit(1)
		}
		defer func() { _ = f.Close() }()
		out = f
	}

	tmplData := templateData{
		Package: *pkgName,
		Tags:    make([]templateTag, 0, len(tags)),
	}
	for _, t := range tags {
		name := tagNames[t.Tag]
		if name == "" {
			name = deriveName(t.Semantics)
		}
		tmplData.Tags = append(tmplData.Tags, templateTag{
			Name:      name,
			Tag:       t.Tag,
			DataItem:  t.DataItem,
			Semantics: t.Semantics,
			Reference: t.Reference,
		})
	}

	if err := genTemplate.Execute(out, tmplData); err != nil {
		fmt.Fprintf(os.Stderr, "error executing template: %v\n", err)
		os.Exit(1)
	}
}

func parseSubset(s string) map[uint64]bool {
	m := make(map[uint64]bool)
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		n, err := strconv.ParseUint(part, 10, 64)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: ignoring invalid subset value %q\n", part)
			continue
		}
		m[n] = true
	}
	return m
}

func deriveName(semantics string) string {
	var b strings.Builder
	upper := true
	for _, r := range semantics {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

type templateData struct {
	Package string
	Tags    []templateTag
}

type templateTag struct {
	Name      string
	Tag       uint64
	DataItem  string
	Semantics string
	Reference string
}

var genTemplate = template.Must(template.New("gen").Parse(`// Code generated by cbor-registry-gen. DO NOT EDIT.

package {{.Package}}

const (
{{- range .Tags}}
	// Tag{{.Name}} is tag {{.Tag}}: {{.Semantics}}.
	Tag{{.Name}} uint64 = {{.Tag}}
{{end}})
`))
